apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: elt-pipeline
type: Opaque
stringData:
  MINIO_ENDPOINT: "minio-service.elt-pipeline.svc.cluster.local:9000"
  MINIO_ACCESS_KEY: "REPLACE_ME"
  MINIO_SECRET_KEY: "REPLACE_ME"
  MINIO_SECURE: "false"
  MINIO_BRONZE_BUCKET: "bronze"
  MINIO_SILVER_BUCKET: "silver"
  MINIO_REGION: "us-east-1"
