apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  namespace: elt-pipeline
type: Opaque
stringData:
  ORACLE_HOST: "oracle-db.company.local"
  ORACLE_PORT: "1521"
  ORACLE_SERVICE_NAME: "ORCL"
  ORACLE_USER: "REPLACE_ME"
  ORACLE_PASSWORD: "REPLACE_ME"
  ORACLE_SCHEMA: "ELT_PIPELINE"
